workflows:

  version: 2.0

  test_and_packaging:

    jobs:

     - test

     - package:

        requires:

          - test
jobs:

  test:

    docker:

      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - run:

        command:

          gradle jar

      - run:

        name: Build and test

        command:

          gradle test

      - store_test_results:

        path: build/test-results

  package:

    docker:

      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - run:

        name: Package and store Artifacts

        command:

          gradle jar

      - store_artifacts:

          path: build/libs

          destination: prefix

