workflows:

  version: 2
  test_and_packaging:

    jobs:
      - package
      - test:
          requires:
            - package
      - dockerize:
          requires:
            - test

jobs:

  test:

    docker:

      - image: circleci/openjdk:8-jdk

    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - my-dependencies-{{ checksum "build.gradle" }}
      - checkout

      - run:

          name: Build and test

          command:

            gradle test

      - store_test_results:

          path: build/test-results
      
     


  package:

    docker:

      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - run:

          name: Package and store Artifacts

          command:

            gradle jar

      - store_artifacts:

          path: build/libs

          destination: output

      - persist_to_workspace:
          root: .
          paths:
            - .
      - save_cache:
          key: my-dependencies-{{ checksum "build.gradle" }}
          paths:
            - my-project/my-dependencies-directory

  dockerize:
    machine: true
    steps:
      - checkout
      # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .

      # deploy the image
      - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1