workflows:

  version: 2
  test_and_packaging:

    jobs:
      - package
      - test:
          requires:
            - package

jobs:

  test:

    docker:

      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - run:

          name: Build and test

          command:

            gradle test

      - store_test_results:

          path: build/test-results
      - attach_workspace:
          at: /pers/ws


  package:

    docker:

      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - run:

          name: Package and store Artifacts

          command:

            gradle jar

      - store_artifacts:

          path: build/libs

          destination: prefix


      - persist_to_workspace:
          root: pers/ws
          paths:
            - build/* 