version: 2.0
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
         name: First Step
         command:
           echo 'Hello world!'
           echo 'This is my delivery pipeline..'
