version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - store_test_results:
         path: test-results
      - run:
         name: First Step
         command:
           gradle test
